datasource:
  mysql:
    url: jdbc:mysql://localhost:3306/petclinic
    username:
    password: 
    driverClassName: com.mysql.jdbc.Driver
  postgres:
    url: jdbc:postgresql://localhost:5432/petclinic
    username:
    password:
    driverClassName: org.postgresql.Driver    

spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      javax.persistence.sharedCache.mode: ALL
      hibernate:
        cache:
          use_second_level_cache: false
          use_query_cache: false
          region:
            factory_class:  org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
          generate_statistics: true

# org.apache.ignite.hibernate.grid_name: petclinic-ignite-grid
# org.apache.ignite.hibernate.default_access_type: READ_WRITE

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/